require('dotenv').config();
const mongoose = require('mongoose');
const Product = require('../models/Product');
const User = require('../models/User');
const connectDB = require('../config/database');

const sampleProducts = [
  // Electronics
  {
    name: 'Apple iPhone 15 Pro Max',
    description: 'The ultimate iPhone with Titanium design, A17 Pro chip, customizable Action button, and a more versatile Pro camera system.',
    price: 1199.99,
    originalPrice: 1299.99,
    category: 'electronics',
    brand: 'Apple',
    images: [{ url: 'https://m.media-amazon.com/images/I/81SigAnNfJL._AC_SL1500_.jpg' }],
    stock: 25,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Storage': '256GB', 'Chip': 'A17 Pro', 'Display': '6.7-inch OLED', 'Color': 'Natural Titanium' },
    tags: ['iphone', 'smartphone', 'apple', 'ios']
  },
  {
    name: 'Apple MacBook Air M2',
    description: 'Strikingly thin and fast, the MacBook Air features the M2 chip, a 13.6-inch Liquid Retina display, and up to 18 hours of battery life.',
    price: 1099,
    originalPrice: 1199,
    category: 'electronics',
    brand: 'Apple',
    images: [{ url: 'https://m.media-amazon.com/images/I/71f5Eu5lJSL._AC_SL1500_.jpg' }],
    stock: 15,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'RAM': '8GB', 'SSD': '256GB', 'Chip': 'M2', 'Weight': '1.24kg' },
    tags: ['laptop', 'macbook', 'apple', 'm2']
  },
  {
    name: 'Sony WH-1000XM5 Headphones',
    description: 'Industry-leading noise cancellation with 8 microphones, Auto NC Optimizer, and incredible sound quality for music and calls.',
    price: 399.99,
    originalPrice: 449.99,
    category: 'electronics',
    brand: 'Sony',
    images: [{ url: 'https://m.media-amazon.com/images/I/41uB-vAn7VL._AC_SL1000_.jpg' }],
    stock: 40,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Battery': '30 hours', 'Noise Cancelling': 'Active', 'Connectivity': 'Bluetooth 5.2' },
    tags: ['headphones', 'sony', 'audio', 'wireless']
  },
  {
    name: 'Samsung 32" Odyssey G7',
    description: 'World\'s first 1000R curved gaming monitor with 240Hz refresh rate and 1ms response time.',
    price: 699.99,
    originalPrice: 799.99,
    category: 'electronics',
    brand: 'Samsung',
    images: [{ url: 'https://m.media-amazon.com/images/I/81PlN33E6gL._AC_SL1500_.jpg' }],
    stock: 12,
    ratings: 4.7,
    isFeatured: false,
    specifications: { 'Resolution': '2560 x 1440', 'Refresh Rate': '240Hz', 'Curve': '1000R' },
    tags: ['monitor', 'gaming', 'samsung', 'curved']
  },

  // Clothing
  {
    name: 'Classic Blue Jeans',
    description: 'The original blue jean since 1873. Straight fit with the iconic button fly.',
    price: 89.50,
    originalPrice: 98.00,
    category: 'fashion',
    brand: 'Levis',
    images: [{ url: 'https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800' }],
    stock: 100,
    ratings: 4.6,
    isFeatured: true,
    specifications: { 'Material': '100% Cotton', 'Fit': 'Straight', 'Care': 'Machine Wash' },
    tags: ['jeans', 'levis', 'denim', 'casual']
  },
  {
    name: 'Men Winter Jacket',
    description: 'The iconic 1996 Retro Nuptse Jacket is packed with 700-fill down for warmth and style.',
    price: 280,
    originalPrice: 320,
    category: 'fashion',
    brand: 'The North Face',
    images: [{ url: 'https://m.media-amazon.com/images/I/71pY893v8vL._AC_SL1500_.jpg' }],
    stock: 30,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'Fill': '700 Down', 'Season': 'Winter', 'Weight': 'Standard' },
    tags: ['jacket', 'northface', 'winter', 'fashion']
  },
  {
    name: 'Premium Wool Overcoat',
    description: 'Elegant tailored overcoat made from a premium wool blend. Perfect for professional and formal occasions.',
    price: 199.99,
    originalPrice: 299.99,
    category: 'fashion',
    brand: 'ShopHub Luxe',
    images: [{ url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?q=80&w=800&auto=format&fit=crop' }],
    stock: 20,
    ratings: 4.5,
    isFeatured: false,
    specifications: { 'Material': 'Wool Blend', 'Fit': 'Slim', 'Lining': 'Satin' },
    tags: ['coat', 'luxury', 'men', 'formal']
  },

  // Home & Kitchen
  {
    name: 'Kitchen Electric Mixer',
    description: 'The legendary KitchenAid stand mixer with 10 speeds and a 5-quart stainless steel bowl.',
    price: 449.99,
    originalPrice: 499.99,
    category: 'home',
    brand: 'KitchenAid',
    images: [{ url: 'https://m.media-amazon.com/images/I/71r9m6iG89L._AC_SL1500_.jpg' }],
    stock: 15,
    ratings: 5.0,
    isFeatured: true,
    specifications: { 'Capacity': '5 Quart', 'Speeds': '10', 'Power': '325W' },
    tags: ['mixer', 'kitchen', 'baking', 'appliance']
  },
  {
    name: 'Nespresso Vertuo Coffee Machine',
    description: 'Automatic coffee and espresso machine that brews 5 cup sizes with a single touch.',
    price: 179,
    originalPrice: 229,
    category: 'home',
    brand: 'Nespresso',
    images: [{ url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800' }],
    stock: 25,
    ratings: 4.6,
    isFeatured: false,
    specifications: { 'Coffee Type': 'Capsules', 'Tank Size': '40oz', 'Heating': '15 seconds' },
    tags: ['coffee', 'nespresso', 'machine', 'kitchen']
  },
  {
    name: 'Dyson V15 Detect Vacuum',
    description: 'Dyson\'s most powerful, intelligent cordless vacuum. Laser reveals microscopic dust.',
    price: 749.99,
    originalPrice: 849.99,
    category: 'home',
    brand: 'Dyson',
    images: [{ url: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=800' }],
    stock: 10,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Suction': '230AW', 'Runtime': '60 min', 'Weight': '3kg' },
    tags: ['vacuum', 'dyson', 'cleaning', 'home']
  },

  // Sports
  {
    name: 'Nike Air Max 270',
    description: 'Nike\'s first lifestyle Air Max delivers style, comfort and big attitude.',
    price: 160,
    originalPrice: 180,
    category: 'sports',
    brand: 'Nike',
    images: [{ url: 'https://m.media-amazon.com/images/I/71oEkC9YMTL._AC_SL1500_.jpg' }],
    stock: 60,
    ratings: 4.7,
    isFeatured: true,
    specifications: { 'Style': 'Athletic', 'Cushion': 'Max Air', 'Color': 'Core Black' },
    tags: ['nike', 'sneakers', 'shoes', 'running']
  },
  {
    name: 'Peloton Bike+',
    description: 'The ultimate immersive indoor cycling experience with a 24-inch rotating touchscreen.',
    price: 2495,
    originalPrice: 2800,
    category: 'sports',
    brand: 'Peloton',
    images: [{ url: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=800' }],
    stock: 5,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'Screen': '23.8" HD', 'Weight': '63kg', 'Resistance': 'Magnetic' },
    tags: ['cycling', 'peloton', 'fitness', 'home-gym']
  },
  {
    name: 'Wilson Pro Staff Tennis Racket',
    description: 'The legendary racket choice of champions, providing ultimate precision and feel.',
    price: 249,
    originalPrice: 279,
    category: 'sports',
    brand: 'Wilson',
    images: [{ url: 'https://images.unsplash.com/photo-1628336707631-670566379555?auto=format&fit=crop&w=800&q=80' }],
    stock: 20,
    ratings: 4.7,
    isFeatured: false,
    specifications: { 'Head Size': '97 sq in', 'Weight': '315g', 'String Pattern': '16x19' },
    tags: ['tennis', 'racket', 'wilson', 'sport']
  },

  // Books
  {
    name: 'The Creative Act by Rick Rubin',
    description: 'A beautiful and generous course of study that illuminates the path of the artist as a road we all can travel.',
    price: 32,
    originalPrice: 45,
    category: 'books',
    brand: 'Penguin Press',
    images: [{ url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800' }],
    stock: 50,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Format': 'Hardcover', 'Pages': '432', 'Language': 'English' },
    tags: ['books', 'art', 'creativity', 'reading']
  },
  {
    name: 'Kindle Paperwhite',
    description: 'Now with a 6.8” display and thinner borders, adjustable warm light, up to 10 weeks of battery life.',
    price: 139.99,
    originalPrice: 159.99,
    category: 'books',
    brand: 'Amazon',
    images: [{ url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d7?auto=format&fit=crop&w=800&q=80' }],
    stock: 35,
    ratings: 4.8,
    isFeatured: false,
    specifications: { 'Display': '6.8 inch', 'Storage': '16GB', 'Battery': '10 weeks' },
    tags: ['kindle', 'ereader', 'books', 'tech']
  },

  // Beauty & Accessories
  {
    name: 'Estée Lauder Advanced Night Repair',
    description: 'Fast visible repair and youth-generating power. Our number 1 serum to help reduce multiple signs of aging.',
    price: 115,
    originalPrice: 125,
    category: 'accessories',
    brand: 'Estée Lauder',
    images: [{ url: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=800' }],
    stock: 45,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'Volume': '50ml', 'Skin Type': 'All types', 'Benefit': 'Repair' },
    tags: ['skincare', 'serum', 'beauty', 'luxury']
  },
  {
    name: 'Dyson Airwrap Multi-Styler',
    description: 'Curl, shape, smooth, and hide flyaways with the Coanda effect. No extreme heat.',
    price: 599.99,
    originalPrice: 650.00,
    category: 'accessories',
    brand: 'Dyson',
    images: [{ url: 'https://images.unsplash.com/photo-1522338140262-f46f5912043a?auto=format&fit=crop&w=800&q=80' }],
    stock: 12,
    ratings: 4.7,
    isFeatured: true,
    specifications: { 'Power': '1300W', 'Settings': '3 heat, 3 speed', 'Weight': '0.7kg' },
    tags: ['haircare', 'dyson', 'styler', 'beauty']
  },

  // Toys & Games
  {
    name: 'LEGO Star Wars Millennium Falcon',
    description: 'Build and display an iconic LEGO Star Wars model with 7,500+ pieces.',
    price: 799.99,
    originalPrice: 849.99,
    category: 'accessories',
    brand: 'LEGO',
    images: [{ url: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=800' }],
    stock: 8,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Pieces': '7541', 'Age': '18+', 'Dimensions': '84cm x 60cm' },
    tags: ['lego', 'starwars', 'toys', 'collectibles']
  },
  {
    name: 'PlayStation 5 Console',
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with haptic feedback.',
    price: 499.99,
    originalPrice: 549.99,
    category: 'electronics',
    brand: 'Sony',
    images: [{ url: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800' }],
    stock: 15,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Storage': '825GB SSD', 'Output': '4K 120Hz', 'Controllers': '1 DualSense' },
    tags: ['ps5', 'gaming', 'console', 'sony']
  },

  // Jewelry & Accessories
  {
    name: 'Ray-Ban Classic Wayfarer',
    description: 'The most recognizable style in the history of sunglasses. A signature style since 1952.',
    price: 163,
    originalPrice: 180,
    category: 'accessories',
    brand: 'Ray-Ban',
    images: [{ url: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800' }],
    stock: 50,
    ratings: 4.7,
    isFeatured: false,
    specifications: { 'Frame': 'Acetate', 'Lens': 'Green Classic G-15', 'Fit': 'Standard' },
    tags: ['sunglasses', 'rayban', 'fashion', 'classic']
  },
  {
    name: 'Tissot Gentleman Automatic',
    description: 'The Tissot Gentleman is a multi-purpose watch, both ergonomic and elegant in any circumstance.',
    price: 775,
    originalPrice: 850,
    category: 'accessories',
    brand: 'Tissot',
    images: [{ url: 'https://images.unsplash.com/photo-1523170671563-430f63602d4b?w=800' }],
    stock: 15,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'Movement': 'Swiss Automatic', 'Power Reserve': '80 hours', 'Water Resistance': '10 bar' },
    tags: ['watch', 'tissot', 'luxury', 'swiss']
  },

  // More variety to reach ~40 products
  {
    name: 'Fujifilm X-T5 Mirrorless Camera',
    description: 'A photography-focused mirrorless camera with 40.2MP sensor and classic dial-driven design.',
    price: 1699,
    originalPrice: 1899,
    category: 'electronics',
    brand: 'Fujifilm',
    images: [{ url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800' }],
    stock: 10,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Sensor': '40.2MP APS-C', 'Video': '6.2K/30p', 'IBIS': '7.0 stops' },
    tags: ['camera', 'fujifilm', 'photography', 'mirrorless']
  },
  {
    name: 'Adidas Ultraboost Light',
    description: 'Experience epic energy with the new Ultraboost Light, our lightest Ultraboost ever.',
    price: 190,
    originalPrice: 210,
    category: 'sports',
    brand: 'Adidas',
    images: [{ url: 'https://images.unsplash.com/photo-1587563871167-1ee9c731aefb?w=800' }],
    stock: 45,
    ratings: 4.7,
    isFeatured: false,
    specifications: { 'Cushion': 'Boost Light', 'Midsole Drop': '10mm', 'Weight': '293g' },
    tags: ['adidas', 'shoes', 'running', 'comfort']
  },
  {
    name: 'Cast Iron Skillet Set',
    description: 'Pre-seasoned cast iron skillet set for searing, sautéing, baking, and frying.',
    price: 65,
    originalPrice: 85,
    category: 'home',
    brand: 'Lodge',
    images: [{ url: 'https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800' }],
    stock: 30,
    ratings: 4.8,
    specifications: { 'Material': 'Cast Iron', 'Sizes': '8", 10", 12"', 'Country': 'USA' },
    tags: ['kitchen', 'cooking', 'skillet', 'iron']
  },
  {
    name: 'Acoustic Guitar Bundle',
    description: 'Full-size acoustic guitar with spruce top, includes gig bag, tuner, and picks.',
    price: 199,
    originalPrice: 249,
    category: 'accessories',
    brand: 'Fender',
    images: [{ url: 'https://images.unsplash.com/photo-1510915361894-db8b60106cb1?w=800' }],
    stock: 20,
    ratings: 4.6,
    specifications: { 'Body': 'Dreadnought', 'Finish': 'Natural', 'Grade': 'Beginner' },
    tags: ['music', 'guitar', 'instrument']
  },
  {
    name: 'Memory Foam Gaming Chair',
    description: 'Premium gaming chair with ergonomic design, 4D armrests, and cooling memory foam.',
    price: 399,
    originalPrice: 499,
    category: 'home',
    brand: 'Secretlab',
    images: [{ url: 'https://images.unsplash.com/photo-1598550476439-6847785fce66?w=800' }],
    stock: 15,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Material': 'Hybrid Leatherette', 'Size': 'Regular', 'Warranty': '5 years' },
    tags: ['chair', 'gaming', 'setup', 'office']
  },
  {
    name: 'Hydro Flask 32oz Wide Mouth',
    description: 'TempShield double-wall vacuum insulation keeps drinks cold for 24h/hot for 12h.',
    price: 44.95,
    originalPrice: 49.95,
    category: 'sports',
    brand: 'Hydro Flask',
    images: [{ url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800' }],
    stock: 80,
    ratings: 4.9,
    specifications: { 'Volume': '32oz', 'Material': 'Stainless Steel', 'BPA Free': 'Yes' },
    tags: ['waterbottle', 'fitness', 'travel', 'outdoors']
  },
  {
    name: 'Fitbit Charge 6',
    description: 'Advanced fitness and health tracker with Google apps, heart rate on gym equipment, and GPS.',
    price: 159,
    originalPrice: 179,
    category: 'electronics',
    brand: 'Fitbit',
    images: [{ url: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800' }],
    stock: 40,
    ratings: 4.5,
    specifications: { 'Battery': '7 days', 'GPS': 'Built-in', 'Water Resistance': '50m' },
    tags: ['fitbit', 'tracker', 'fitness', 'health']
  },
  {
    name: 'La Mer Moisturizing Cream',
    description: 'The moisturizer that started it all. Legendary Crème de la Mer has the power to transform skin.',
    price: 380,
    originalPrice: 420,
    category: 'accessories',
    brand: 'La Mer',
    images: [{ url: 'https://images.unsplash.com/photo-1617897903246-719242758050?w=800' }],
    stock: 10,
    ratings: 4.7,
    specifications: { 'Volume': '60ml', 'Key Ingredient': 'Miracle Broth', 'Benefit': 'Renewal' },
    tags: ['luxury', 'skincare', 'lamer', 'beauty']
  },
  {
    name: 'Patagonia Better Sweater',
    description: 'Warm, low-bulk full-zip jacket made of soft polyester sweater-knit face and fleece interior.',
    price: 149,
    originalPrice: 169,
    category: 'fashion',
    brand: 'Patagonia',
    images: [{ url: 'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800' }],
    stock: 25,
    ratings: 4.9,
    specifications: { 'Material': 'Recycled Polyester', 'Weight': 'Midweight', 'Fair Trade': 'Yes' },
    tags: ['patagonia', 'fleece', 'sustainable', 'outdoor']
  },
  {
    name: 'Anker 737 Power Bank',
    description: 'Ultra-powerful 140W power bank with digital display and 24,000mAh capacity.',
    price: 149.99,
    originalPrice: 169.99,
    category: 'electronics',
    brand: 'Anker',
    images: [{ url: 'https://images.unsplash.com/photo-1593941707882-a5bba1491017?w=800' }],
    stock: 50,
    ratings: 4.8,
    specifications: { 'Capacity': '24,000mAh', 'Output': '140W Max', 'Ports': '2 USB-C, 1 USB-A' },
    tags: ['powerbank', 'anker', 'charging', 'tech']
  },
  {
    name: 'Herman Miller Aeron Chair',
    description: 'The benchmark for ergonomic seating. Breathable, comfortable, and iconic.',
    price: 1805,
    originalPrice: 2000,
    category: 'home',
    brand: 'Herman Miller',
    images: [{ url: 'https://images.unsplash.com/photo-1589384273441-c5df2f9131be?w=800' }],
    stock: 5,
    ratings: 5.0,
    isFeatured: true,
    specifications: { 'Size': 'Medium (B)', 'Lumbar': 'PostureFit SL', 'Warranty': '12 years' },
    tags: ['office', 'chair', 'ergonomic', 'luxury']
  },
  {
    name: 'Logitech MX Master 3S',
    description: 'Performance wireless mouse with 8K DPI tracking and quiet clicks.',
    price: 99,
    originalPrice: 109,
    category: 'electronics',
    brand: 'Logitech',
    images: [{ url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800' }],
    stock: 75,
    ratings: 4.9,
    specifications: { 'Sensor': '8,000 DPI', 'Battery': '70 days', 'Flow': 'Multi-device' },
    tags: ['logitech', 'mouse', 'productivity', 'wireless']
  },
  {
    name: 'Kindle Scribe',
    description: 'The first Kindle for reading and writing, with a 10.2” 300 ppi Paperwhite display and included Basic Pen.',
    price: 339,
    originalPrice: 389,
    category: 'books',
    brand: 'Amazon',
    images: [{ url: 'https://images.unsplash.com/photo-1621259182978-f09e5e2ca1ff?w=800' }],
    stock: 12,
    ratings: 4.6,
    specifications: { 'Display': '10.2 inch', 'Storage': '16GB', 'Pen': 'Included' },
    tags: ['kindle', 'notebook', 'ereader', 'tech']
  },
  {
    name: 'Yeti Tundra 45 Cooler',
    description: 'Virtually indestructible cooler with PermaFrost insulation to keep your ice cold.',
    price: 325,
    originalPrice: 350,
    category: 'sports',
    brand: 'Yeti',
    images: [{ url: 'https://images.unsplash.com/photo-1616455579100-2ceaa4eb2d37?w=800' }],
    stock: 15,
    ratings: 4.9,
    specifications: { 'Capacity': '26 cans', 'Weight': '10.4kg', 'Ice Retention': '5+ days' },
    tags: ['yeti', 'cooler', 'camping', 'outdoors']
  },
  {
    name: 'Theragun Pro G5',
    description: 'Professional-grade percussive therapy device to relieve pain, improve motion, and enhance recovery.',
    price: 599,
    originalPrice: 650,
    category: 'accessories',
    brand: 'Therabody',
    images: [{ url: 'https://images.unsplash.com/photo-1632732939023-e29864275155?w=800' }],
    stock: 10,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'Force': '60lbs', 'Speed': '5 built-in', 'Battery': '150 min' },
    tags: ['recovery', 'massage', 'fitness', 'wellness']
  },
  {
    name: 'Moleskine Classic Notebook',
    description: 'Hardcover large notebook with 240 ruled pages. The classic choice for writers and artists.',
    price: 24,
    originalPrice: 28,
    category: 'books',
    brand: 'Moleskine',
    images: [{ url: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=800' }],
    stock: 100,
    ratings: 4.7,
    specifications: { 'Size': '5" x 8.25"', 'Pages': '240', 'Paper': 'Acid-free' },
    tags: ['notebook', 'stationery', 'writing', 'moleskine']
  },
  {
    name: 'GoPro HERO12 Black',
    description: 'Incredible image quality, even better HyperSmooth video stabilization and a huge boost in battery life.',
    price: 399,
    originalPrice: 449,
    category: 'electronics',
    brand: 'GoPro',
    images: [{ url: 'https://images.unsplash.com/photo-1629131726692-1accd0c53ce0?w=800' }],
    stock: 25,
    ratings: 4.8,
    specifications: { 'Resolution': '5.3K60', 'Stabilization': 'HyperSmooth 6.0', 'Waterproof': '10m' },
    tags: ['gopro', 'camera', 'action', 'video']
  },
  {
    name: 'Vitamix A3500 Ascent',
    description: 'Professional-grade blender with 5 program settings and a built-in timer.',
    price: 649,
    originalPrice: 699,
    category: 'home',
    brand: 'Vitamix',
    images: [{ url: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800' }],
    stock: 15,
    ratings: 5.0,
    isFeatured: true,
    specifications: { 'Power': '2.2 HP', 'Container': '64oz', 'Warranty': '10 years' },
    tags: ['blender', 'kitchen', 'vitamix', 'cooking']
  },
  {
    name: 'Sony PlayStation 5 DualSense Edge',
    description: 'Built with high performance and personalization in mind, this new PS5 controller invites you to craft your own unique gaming experience.',
    price: 199.99,
    originalPrice: 219.99,
    category: 'electronics',
    brand: 'Sony',
    images: [{ url: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=800' }],
    stock: 20,
    ratings: 4.8,
    specifications: { 'Type': 'Wireless', 'Compatibility': 'PS5, PC', 'Features': 'Haptic Feedback' },
    tags: ['ps5', 'controller', 'gaming', 'sony']
  },
  {
    name: 'Canon EOS R6 Mark II',
    description: 'The EOS R6 Mark II is the most advanced full-frame mirrorless camera from Canon yet, with high-speed continuous shooting.',
    price: 2499,
    originalPrice: 2699,
    category: 'electronics',
    brand: 'Canon',
    images: [{ url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800' }],
    stock: 8,
    ratings: 4.9,
    specifications: { 'Sensor': '24.2MP Full-Frame', 'Video': '4K 60p', 'AF': 'Dual Pixel CMOS AF II' },
    tags: ['camera', 'canon', 'photography', 'mirrorless']
  },
  {
    name: 'Nike Tech Fleece Hoodie',
    description: 'Premium, lightweight fleece—smooth both inside and out—gives you plenty of warmth without adding bulk.',
    price: 130,
    originalPrice: 145,
    category: 'fashion',
    brand: 'Nike',
    images: [{ url: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800' }],
    stock: 50,
    ratings: 4.7,
    specifications: { 'Material': '66% Cotton/34% Polyester', 'Fit': 'Standard', 'Care': 'Machine Wash' },
    tags: ['nike', 'hoodie', 'techfleece', 'fashion']
  },
  {
    name: 'Ralph Lauren Polo Shirt',
    description: 'An American style standard since 1972, this Polo shirt is crafted from highly breathable cotton mesh.',
    price: 98,
    originalPrice: 115,
    category: 'fashion',
    brand: 'Ralph Lauren',
    images: [{ url: 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=800' }],
    stock: 40,
    ratings: 4.6,
    specifications: { 'Material': '100% Cotton', 'Fit': 'Slim Fit', 'Care': 'Laundry' },
    tags: ['polo', 'classic', 'fashion', 'men']
  },
  {
    name: 'Logitech G Pro X Superlight 2',
    description: 'The world\'s fastest pro gaming mouse now in its second generation with LIGHTFORCE hybrid switches.',
    price: 159,
    originalPrice: 179,
    category: 'electronics',
    brand: 'Logitech',
    images: [{ url: 'https://images.unsplash.com/photo-1527814732934-94a1fe71193d?w=800' }],
    stock: 30,
    ratings: 4.9,
    specifications: { 'Sensor': 'HERO 2', 'Weight': '60g', 'Battery': '95 hours' },
    tags: ['gaming', 'mouse', 'logitech', 'wireless']
  },
  {
    name: 'Apple Watch Ultra 2',
    description: 'The most rugged and capable Apple Watch. Now with a brighter display and faster chip.',
    price: 799,
    originalPrice: 849,
    category: 'electronics',
    brand: 'Apple',
    images: [{ url: 'https://images.unsplash.com/photo-1434493907317-a46b53b81882?w=800' }],
    stock: 20,
    ratings: 4.8,
    isFeatured: true,
    specifications: { 'Case': 'Titanium', 'Display': '3000 nits', 'Battery': '36 hours' },
    tags: ['watch', 'smartwatch', 'apple', 'ultra']
  },
  {
    name: 'Samsung Galaxy S24 Ultra',
    description: 'Welcome to the era of mobile AI. With Galaxy S24 Ultra, you can unleash whole new levels of creativity.',
    price: 1299,
    originalPrice: 1399,
    category: 'electronics',
    brand: 'Samsung',
    images: [{ url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800' }],
    stock: 25,
    ratings: 4.9,
    specifications: { 'Display': '6.8" AMOLED', 'Storage': '256GB', 'Camera': '200MP' },
    tags: ['samsung', 'android', 'phone', 'ai']
  },
  {
    name: 'Sony A7 IV Mirrorless Camera',
    description: 'Beyond basic. Capture your vision with the stunning resolution and precision of the Alpha 7 IV.',
    price: 2499,
    originalPrice: 2699,
    category: 'electronics',
    brand: 'Sony',
    images: [{ url: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800' }],
    stock: 10,
    ratings: 4.9,
    specifications: { 'Sensor': '33MP Full Frame', 'Video': '4K 60p', 'IBIS': '5.5 stops' },
    tags: ['camera', 'sony', 'photography', 'pro']
  },
  {
    name: 'Bose QuietComfort Ultra',
    description: 'World-class noise cancellation, quieter than ever before. New spatial audio for immersive listening.',
    price: 429,
    originalPrice: 479,
    category: 'electronics',
    brand: 'Bose',
    images: [{ url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800' }],
    stock: 35,
    ratings: 4.8,
    specifications: { 'Battery': '24 hours', 'Immersive Audio': 'Yes', 'Charging': 'USB-C' },
    tags: ['headphones', 'bose', 'audio', 'wireless']
  },
  {
    name: 'Razer Blade 16 Gaming Laptop',
    description: 'Experience pure gaming power with the Razer Blade 16, featuring the world\'s first dual-mode mini-LED display.',
    price: 2999,
    originalPrice: 3299,
    category: 'electronics',
    brand: 'Razer',
    images: [{ url: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800' }],
    stock: 8,
    ratings: 4.7,
    isFeatured: true,
    specifications: { 'GPU': 'RTX 4090', 'CPU': 'i9-13950HX', 'RAM': '32GB' },
    tags: ['gaming', 'laptop', 'razer', 'performance']
  },
  {
    name: 'Ergonomic Standing Desk',
    description: 'Transition smoothly from sitting to standing with our dual-motor electric standing desk.',
    price: 450,
    originalPrice: 550,
    category: 'home',
    brand: 'FlexiSpot',
    images: [{ url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?w=800' }],
    stock: 20,
    ratings: 4.8,
    specifications: { 'Width': '55 inches', 'Motors': 'Dual', 'Material': 'Bamboo' },
    tags: ['desk', 'office', 'home', 'setup']
  },
  {
    name: 'Morden Velvet Sofa',
    description: 'Luxurious velvet upholstery with deep-tufting and custom turned legs. A statement piece for any living room.',
    price: 1200,
    originalPrice: 1500,
    category: 'home',
    brand: 'West Elm',
    images: [{ url: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800' }],
    stock: 5,
    ratings: 4.9,
    specifications: { 'Seating': '3 Person', 'Fabric': 'Velvet', 'Color': 'Emerald Green' },
    tags: ['furniture', 'sofa', 'luxury', 'livingroom']
  },
  {
    name: 'Chef\'s Knife 8-Inch',
    description: 'Precision-forged from high-carbon German steel. The ultimate tool for every kitchen task.',
    price: 145,
    originalPrice: 175,
    category: 'home',
    brand: 'Wusthof',
    images: [{ url: 'https://images.unsplash.com/photo-1593642634367-d91a135567b5?w=800' }],
    stock: 50,
    ratings: 5.0,
    specifications: { 'Length': '8 inch', 'Steel': 'German', 'Balance': 'Full Bolster' },
    tags: ['knife', 'chef', 'kitchen', 'cooking']
  },
  {
    name: 'Women Designer Handbag',
    description: 'Iconic quilted leather handbag with gold-tone hardware. Timeless elegance for any outfit.',
    price: 2500,
    originalPrice: 2800,
    category: 'fashion',
    brand: 'ShopHub Luxe',
    images: [{ url: 'https://images.unsplash.com/photo-1584917033904-491a7c3938be?w=800' }],
    stock: 10,
    ratings: 4.9,
    isFeatured: true,
    specifications: { 'Material': 'Lambskin', 'Size': 'Medium', 'Hardware': 'Gold' },
    tags: ['bag', 'luxury', 'fashion', 'women']
  },
  {
    name: 'Classic Silk Scarve',
    description: '100% pure silk scarf with hand-rolled edges. Features a unique botanical print.',
    price: 85,
    originalPrice: 120,
    category: 'fashion',
    brand: 'Accessories Co',
    images: [{ url: 'https://images.unsplash.com/photo-1583939411023-1478287c8b94?w=800' }],
    stock: 100,
    ratings: 4.7,
    specifications: { 'Material': '100% Silk', 'Dimensions': '90x90 cm', 'Origin': 'Italy' },
    tags: ['scarf', 'silk', 'fashion', 'accessories']
  },
  {
    name: 'Yoga Mat Pro',
    description: 'Ultra-dense 6mm yoga mat with non-slip texture for superior grip and cushioning.',
    price: 55,
    originalPrice: 75,
    category: 'sports',
    brand: 'Lululemon',
    images: [{ url: 'https://images.unsplash.com/photo-1592434134753-a70baf7979d7?w=800' }],
    stock: 150,
    ratings: 4.8,
    specifications: { 'Thickness': '6mm', 'Material': 'Eco-friendly TPE', 'Weight': '1kg' },
    tags: ['yoga', 'fitness', 'mat', 'health']
  },
  {
    name: 'Adjustable Dumbbells Set',
    description: 'High-quality adjustable dumbbells that replace 15 sets of weights. Quick-turn dial system.',
    price: 349,
    originalPrice: 449,
    category: 'sports',
    brand: 'Bowflex',
    images: [{ url: 'https://images.unsplash.com/photo-1583454110551-21f2fa200c01?w=800' }],
    stock: 30,
    ratings: 4.9,
    specifications: { 'Weight Range': '5-52.5 lbs', 'Dial': 'Automatic', 'Stand': 'Available' },
    tags: ['fitness', 'gym', 'dumbbells', 'strength']
  },
  {
    name: 'Nintendo Switch OLED',
    description: 'Play at home on the TV or on-the-go with a vibrant 7-inch OLED screen.',
    price: 349.99,
    originalPrice: 399.99,
    category: 'electronics',
    brand: 'Nintendo',
    images: [{ url: 'https://images.unsplash.com/photo-1578303328516-30230058e452?w=800' }],
    stock: 40,
    ratings: 4.9,
    specifications: { 'Display': '7" OLED', 'Battery': '4.5-9 hours', 'Storage': '64GB' },
    tags: ['gaming', 'switch', 'nintendo', 'handheld']
  },
  {
    name: 'Electric Standing Heater',
    description: 'Keep your patio warm all year round with this high-efficiency infrared standing heater.',
    price: 220,
    originalPrice: 280,
    category: 'home',
    brand: 'EcoWarm',
    images: [{ url: 'https://images.unsplash.com/photo-1585336261022-69c66d11efec?w=800' }],
    stock: 15,
    ratings: 4.5,
    specifications: { 'Power': '1500W', 'Height': '6.5 feet', 'Weatherproof': 'Yes' },
    tags: ['heater', 'home', 'outdoor', 'winter']
  },
  {
    name: 'Premium Coffee Grinder',
    description: 'Conical burr grinder with 40 adjustable settings to produce the perfect grounds for any brew.',
    price: 189,
    originalPrice: 220,
    category: 'home',
    brand: 'Baratza',
    images: [{ url: 'https://images.unsplash.com/photo-1589384273441-c5df2f9131be?w=800' }],
    stock: 25,
    ratings: 4.8,
    specifications: { 'Burrs': 'Stainless Steel', 'Settings': '40', 'Capacity': '250g' },
    tags: ['coffee', 'grinder', 'brewing', 'kitchen']
  },
  {
    name: 'Designer Sunglasses',
    description: 'Contemporary oversized frames with gradient lenses. Total UV protection with a bold look.',
    price: 350,
    originalPrice: 420,
    category: 'accessories',
    brand: 'Prada',
    images: [{ url: 'https://images.unsplash.com/photo-1511499767390-903390e62bc0?w=800' }],
    stock: 20,
    ratings: 4.6,
    specifications: { 'Frame': 'Acetate', 'Lens': 'Gradient Grey', 'UV': '100% Protection' },
    tags: ['sunglasses', 'luxury', 'fashion', 'eyewear']
  },
  {
    name: 'Smart WiFi LED Bulb',
    description: 'Control your lighting from anywhere with your smartphone or voice commands. Millions of colors.',
    price: 15,
    originalPrice: 25,
    category: 'home',
    brand: 'Philips Hue',
    images: [{ url: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=800' }],
    stock: 500,
    ratings: 4.7,
    specifications: { 'Brightness': '800 lumens', 'Connectivity': 'WiFi/Bluetooth', 'Lifespan': '25,000 hours' },
    tags: ['lighting', 'smart', 'home', 'iot']
  },
  {
    name: 'Electric Skateboard',
    description: 'High-performance electric skateboard with dual motors and regenerative braking. Top speed of 25mph.',
    price: 599,
    originalPrice: 799,
    category: 'sports',
    brand: 'Boosted',
    images: [{ url: 'https://images.unsplash.com/photo-1547447134-cd3f5c716030?w=800' }],
    stock: 12,
    ratings: 4.8,
    specifications: { 'Top Speed': '25 mph', 'Range': '14 miles', 'Weight': '7kg' },
    tags: ['skateboard', 'electric', 'travel', 'sports']
  },
  {
    name: 'Settlers of Catan Game',
    description: 'The award-winning strategy game where players trade and build their way to victory on the island of Catan.',
    price: 55,
    originalPrice: 65,
    category: 'books',
    brand: 'Catan Studio',
    images: [{ url: 'https://images.unsplash.com/photo-1610812383749-92f754fc3950?w=800' }],
    stock: 60,
    ratings: 4.9,
    specifications: { 'Players': '3-4', 'Age': '10+', 'Duration': '60-90 min' },
    tags: ['boardgame', 'strategy', 'family', 'fun']
  },
  {
    name: 'Smart Doorbell WiFi',
    description: 'See, hear, and speak to visitors from anywhere with our 1080p HD video doorbell.',
    price: 129,
    originalPrice: 159,
    category: 'home',
    brand: 'Ring',
    images: [{ url: 'https://images.unsplash.com/photo-1558002038-1055907df827?q=80&w=800&auto=format&fit=crop' }],
    stock: 45,
    ratings: 4.6,
    specifications: { 'Resolution': '1080p', 'Field of View': '160 degrees', 'Battery': 'Removable' },
    tags: ['doorbell', 'smart', 'security', 'home']
  },
  {
    name: 'Electric Standing Desk',
    description: 'Work healthier with our electric height-adjustable standing desk. Preset your favorite heights.',
    price: 349,
    originalPrice: 449,
    category: 'home',
    brand: 'FlexiSpot',
    images: [{ url: 'https://images.unsplash.com/photo-1595515106969-1ce29566ff1c?q=80&w=800&auto=format&fit=crop' }],
    stock: 15,
    ratings: 4.8,
    specifications: { 'Range': '28"-47"', 'Weight Capacity': '154 lbs', 'Material': 'Steel' },
    tags: ['desk', 'office', 'home', 'furniture']
  },
  {
    name: 'Designer Cotton T-Shirt',
    description: 'Stay comfortable and stylish with our premium 100% organic cotton T-shirt.',
    price: 25,
    originalPrice: 35,
    category: 'fashion',
    brand: 'Uniqlo',
    images: [{ url: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?q=80&w=800&auto=format&fit=crop' }],
    stock: 200,
    ratings: 4.5,
    specifications: { 'Material': '100% Organic Cotton', 'Fit': 'Regular', 'Color': 'White' },
    tags: ['shirt', 'tshirt', 'casual', 'fashion']
  },
  {
    name: 'Air Purifier with HEPA Filter',
    description: 'Breathe cleaner air with our advanced HEPA air purifier. Removes 99.97% of dust and smoke.',
    price: 89,
    originalPrice: 109,
    category: 'home',
    brand: 'Levoit',
    images: [{ url: 'https://images.unsplash.com/photo-1585771724684-2626ef952993?q=80&w=800&auto=format&fit=crop' }],
    stock: 30,
    ratings: 4.7,
    specifications: { 'Coverage': '129 sq ft', 'Filter Type': '3-stage HEPA', 'Noise': 'Low' },
    tags: ['air', 'purifier', 'home', 'health']
  },
  {
    name: 'Cast Iron Dutch Oven',
    description: 'Versatile 6-quart enameled cast iron Dutch oven. Perfect for slow cooking and baking.',
    price: 69,
    originalPrice: 89,
    category: 'home',
    brand: 'Lodge',
    images: [{ url: 'https://images.unsplash.com/photo-1590794144397-064df6f9c3fd?q=80&w=800&auto=format&fit=crop' }],
    stock: 25,
    ratings: 4.9,
    specifications: { 'Capacity': '6 Quart', 'Material': 'Cast Iron', 'Oven Safe': 'Yes' },
    tags: ['cooking', 'dutchoven', 'pot', 'home']
  },
  {
    name: 'Bluetooth Shower Speaker',
    description: 'Waterproof Bluetooth speaker with suction cup. Listen to music or take calls in the shower.',
    price: 19,
    originalPrice: 29,
    category: 'electronics',
    brand: 'Anker',
    images: [{ url: 'https://images.unsplash.com/photo-1608155613957-31f030bc355a?q=80&w=800&auto=format&fit=crop' }],
    stock: 100,
    ratings: 4.3,
    specifications: { 'Waterproof': 'IPX7', 'Battery': '10 hours', 'Connectivity': 'Bluetooth 5.0' },
    tags: ['speaker', 'audio', 'electronics', 'fun']
  },
  {
    name: 'Adjustable Dumbbells Set',
    description: 'Space-saving adjustable dumbbells. Select weight from 5 to 50 lbs with a turn of a dial.',
    price: 299,
    originalPrice: 399,
    category: 'sports',
    brand: 'Bowflex',
    images: [{ url: 'https://images.unsplash.com/photo-1583454110551-21f2fa200c01?q=80&w=800&auto=format&fit=crop' }],
    stock: 12,
    ratings: 4.8,
    specifications: { 'Weight Range': '5-50 lbs', 'Number of Weights': '2', 'Warranty': '2 years' },
    tags: ['gym', 'dumbbells', 'sports', 'fitness']
  },
  {
    name: 'Men\'s Running Shorts',
    description: 'Lightweight and breathable running shorts with moisture-wicking technology.',
    price: 18,
    originalPrice: 25,
    category: 'sports',
    brand: 'Adidas',
    images: [{ url: 'https://images.unsplash.com/photo-1591117207239-788cd4740c67?q=80&w=800&auto=format&fit=crop' }],
    stock: 80,
    ratings: 4.4,
    specifications: { 'Material': 'Polyester', 'Fit': 'Athletic', 'Wash': 'Machine' },
    tags: ['shorts', 'running', 'sport', 'men']
  },
  {
    name: 'Kitchen Bamboo Utensil Set',
    description: '100% organic bamboo cooking utensils. Safe for non-stick cookware.',
    price: 12,
    originalPrice: 20,
    category: 'home',
    brand: 'GreenLife',
    images: [{ url: 'https://images.unsplash.com/photo-1594385209355-667083279148?q=80&w=800&auto=format&fit=crop' }],
    stock: 150,
    ratings: 4.6,
    specifications: { 'Material': 'Bamboo', 'Includes': '7 pieces', 'Dishwasher': 'No' },
    tags: ['utensils', 'kitchen', 'home', 'cooking']
  },
  {
    name: 'Classic White Sneakers',
    description: 'Minimalist white leather sneakers. A versatile addition to any wardrobe.',
    price: 65,
    originalPrice: 85,
    category: 'fashion',
    brand: 'Vans',
    images: [{ url: 'https://images.unsplash.com/photo-1560769629-975ec94e6a86?q=80&w=800&auto=format&fit=crop' }],
    stock: 60,
    ratings: 4.5,
    specifications: { 'Material': 'Leather/Suede', 'Style': 'Low-top', 'Gender': 'Unisex' },
    tags: ['shoes', 'sneakers', 'fashion', 'men']
  },
  {
    name: 'Ceramic Table Lamp',
    description: 'Elegant ceramic table lamp with linen shade. Adds a soft warm glow to any room.',
    price: 45,
    originalPrice: 65,
    category: 'home',
    brand: 'Crate & Barrel',
    images: [{ url: 'https://images.unsplash.com/photo-1550985616-10810253b84d?q=80&w=800&auto=format&fit=crop' }],
    stock: 25,
    ratings: 4.7,
    specifications: { 'Material': 'Ceramic', 'Weight': '2kg', 'Power': '60W' },
    tags: ['lamp', 'home', 'decoration']
  },
  {
    name: 'Stainless Steel Water Bottle',
    description: 'Double-walled insulated water bottle. Keeps drinks cold for 24h/hot for 12h.',
    price: 20,
    originalPrice: 30,
    category: 'sports',
    brand: 'Swell',
    images: [{ url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?q=80&w=800&auto=format&fit=crop' }],
    stock: 120,
    ratings: 4.8,
    specifications: { 'Material': 'Stainless Steel', 'Capacity': '500ml', 'BPA Free': 'Yes' },
    tags: ['bottle', 'fitness', 'sports', 'travel']
  },
  {
    name: 'Instant Pot Duo Plus',
    description: 'Instant Pot Duo Plus is the next generation in the Duo series, the #1 best-selling family in the Instant Pot family.',
    price: 129,
    originalPrice: 149,
    category: 'home',
    brand: 'Instant Pot',
    images: [{ url: 'https://images.unsplash.com/photo-1584286595398-a59b9e602970?w=800' }],
    stock: 40,
    ratings: 4.8,
    specifications: { 'Capacity': '6 Quart', 'Functions': '9-in-1', 'Power': '1000W' },
    tags: ['cooker', 'kitchen', 'instantpot', 'appliance']
  },
  {
    name: 'Bose SoundLink Revolve+ II',
    description: 'Deep, loud and immersive, too. This 360° speaker was engineered to spread deep, jaw-dropping sound in every direction.',
    price: 299,
    originalPrice: 329,
    category: 'electronics',
    brand: 'Bose',
    images: [{ url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800' }],
    stock: 25,
    ratings: 4.7,
    specifications: { 'Battery': '17 hours', 'Water Resistance': 'IP55', 'Range': '30ft' },
    tags: ['speaker', 'bose', 'audio', 'bluetooth']
  },
  {
    name: 'Spalding NBA Zi/O Excel Basketball',
    description: 'The Spalding NBA Zi/O Excel is designed for the competitive player who wants a ball with a tacky feel and exceptional control.',
    price: 35,
    originalPrice: 45,
    category: 'sports',
    brand: 'Spalding',
    images: [{ url: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800' }],
    stock: 60,
    ratings: 4.5,
    specifications: { 'Size': 'Official Size 7', 'Material': 'Composite Leather', 'Use': 'Indoor/Outdoor' },
    tags: ['basketball', 'spalding', 'sports', 'ball']
  },
  {
    name: 'The Alchemist by Paulo Coelho',
    description: 'A global phenomenon, The Alchemist has been read and loved by over sixty-two million readers, becoming a modern classic.',
    price: 15,
    originalPrice: 22,
    category: 'books',
    brand: 'HarperOne',
    images: [{ url: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=800' }],
    stock: 150,
    ratings: 4.9,
    specifications: { 'Format': 'Paperback', 'Pages': '208', 'Language': 'English' },
    tags: ['book', 'fiction', 'classic', 'adventure']
  },
  {
    name: 'Fjallraven Kanken Backpack',
    description: 'Classic Kanken backpack in hard-wearing Vinylon fabric with a zip that opens the entire main compartment.',
    price: 80,
    originalPrice: 90,
    category: 'fashion',
    brand: 'Fjallraven',
    images: [{ url: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800' }],
    stock: 45,
    ratings: 4.8,
    specifications: { 'Volume': '16L', 'Material': 'Vinylon F', 'Weight': '300g' },
    tags: ['backpack', 'fashion', 'kanken', 'outdoor']
  }
];

const seedProducts = async () => {
  try {
    await connectDB();

    console.log('🗑️  Deleting existing products...');
    await Product.deleteMany();

    console.log('👤 Creating admin user...');

    // Delete existing admin if exists
    await User.deleteOne({ email: process.env.ADMIN_EMAIL });

    const admin = await User.create({
      name: 'Admin User',
      email: process.env.ADMIN_EMAIL || 'admin@ecommerce.com',
      password: process.env.ADMIN_PASSWORD || 'Admin123',
      role: 'admin'
    });

    console.log('✅ Admin created:', admin.email);

    // Add admin as creator to products
    const productsWithAdmin = sampleProducts.map(product => ({
      ...product,
      createdBy: admin._id
    }));

    console.log('📦 Seeding products...');
    await Product.insertMany(productsWithAdmin);

    console.log('✅ Database seeded successfully!');
    console.log(`📊 ${sampleProducts.length} products added`);
    console.log('\n🔑 Admin Credentials:');
    console.log(`   Email: ${admin.email}`);
    console.log(`   Password: ${process.env.ADMIN_PASSWORD || 'Admin123'}`);

    process.exit(0);
  } catch (error) {
    console.error('❌ Error seeding database:', error);
    process.exit(1);
  }
};

seedProducts();
